---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: Policies
  label: Policies
  create: all
  match: "**/*.md"
  templates:
  - shipping-and-returns
- type: directory
  path: src/faq
  label: FAQ
  create: all
  match: "**/*.md"
  templates:
  - faq
- type: directory
  path: src/products
  label: Products
  create: all
  match: "**/*.md"
  templates:
  - products
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
